### ISSUE TITLE
Confusing error message when variable is Nothing

### ISSUE THREAD

**Issue by duijf** [nushell/nushell#10506]
### Describe the bug

The error message when `Nothing` interacts with records is a little confusing and can be improved.

### How to reproduce

This is a reduced example, I was writing this in the context of a larger program.

```
$ cat foo.nu
#!/usr/bin/env -S nu --stdin
def main [
  --host: string
] {
  {scheme: s3 host: $host } | url join
}

$ ./foo.nu
Error: nu::shell::missing_parameter

  × Missing parameter: host.
   ╭─[/home/duijf/foo.nu:4:1]
 4 │ ] {
 5 │   {scheme: s3 host: $host } | url join
   ·   ────────────┬────────────
   ·               ╰── missing parameter: host
 6 │ }
   ╰────
```

### Expected behavior

I was a little confused since the error message mentions `missing parameter: host` while the parameter appears in the error itself. This was part of a larger program, so the cause here wasn't obvious to me immediately: I spent some time double checking if I hadn't made a weird typo, etc. until I realised that `$host` is `Nothing`.

It might be nice to change the wording of the error or a hint to improve this message.

### Configuration

This is on NixOS unstable:

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.85.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23) (built from a source tarball) |
| cargo_version      | cargo 1.72.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
What is your suggestion for changing the error message?

You could also make your host parameter have a default like:
```nushell
❯ cat foo.nu
#!/usr/bin/env -S nu --stdin
def main [
  --host(-h): string = "default"
] {
  {scheme: s3 host: $host} | url join
}
```

**Comment by duijf** [comment]
What do you think about something like this? (Not sure if 'empty' is the right word here + if this is at all feasible to implement)

```
  × Required variable is empty.
   ╭─[/home/duijf/foo.nu:4:1]
 4 │ ] {
 5 │   {scheme: s3 host: $host } | url join
   ·                     ──┬──
   ·                       ╰── variable is empty, but required to be non-empty by `url join`
 6 │ }
   ╰────
```

Kind of inspired by what happens in the REPL:

```
> { scheme: asdf, host: $host }
Error: nu::parser::variable_not_found

  × Variable not found.
   ╭─[entry #2:1:1]
 1 │ { scheme: asdf, host: $host }
   ·                       ──┬──
   ·                         ╰── variable not found.
   ╰────
```

**Comment by amtoine** [comment]
because `$.scheme` and `$.host` are the two only required fields, maybe something like the following could make sense?

```nushell
Error: nu::shell::missing_parameter

  × Missing parameter: host.
   ╭─[entry #8:1:1]
 1 │ {scheme: "foo", host: $host} | url join
   ·                       ──┬──
   ·                         ╰── expected string, found nothing
   ╰────
```

**Comment by amtoine** [comment]
on a related note, about what fields are required by `url join`, i feel like the following should at least give a warning? :open_mouth: 
```nushell
> {scheme: "foo", host: "bar", im_not_a_url_field: "hi"} | url join
foo://bar
```

**Comment by sholderbach** [comment]
Has this been fully resolved by #10565?

**Comment by amtoine** [comment]
> Has this been fully resolved by #10565?
>
@sholderbach 
i do not think so, i still get
```nushell
> nu foo.nu
Error: nu::shell::missing_parameter

  × Missing parameter: host.
   ╭─[/home/amtoine/documents/repos/github.com/amtoine/nushell/foo.nu:4:1]
 4 │ ] {
 5 │   {scheme: s3 host: $host } | url join
   ·   ────────────┬────────────
   ·               ╰── missing parameter: host
 6 │ }
   ╰────
```
however, with #10565, we would get a nice
```nushell
> {scheme: "https", host: "github.com", foo: "bar"} | url join
Error:   × 'foo' is not a valid URL field
   ╭─[entry #8:1:1]
 1 │ {scheme: "https", host: "github.com", foo: "bar"} | url join
   · ────────────────────────┬────────────────────────
   ·                         ╰── Remove 'foo' col from input record
   ╰────


https://github.com
```
