### ISSUE TITLE
windows terminal tab title not restoring after a command execution

### ISSUE THREAD

**Issue by sibouras** [nushell/nushell#10703]
### Describe the bug

some programs like `npm`, `lazygit`, `stylua` change the title after executing and after executing the title should be restored like in powershell or cmd, but in nushell the title doesn't restore to its previous state.

### How to reproduce

npm help

### Expected behavior

the title should be restored after the command is finished executing

### Screenshots

https://github.com/nushell/nushell/assets/64098483/9052e459-d3c6-4929-93b1-615c101eba62

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.85.0                                         |
| branch             |                                                |
| commit_hash        | a6f62e05ae5b4e9ba4027fbfffd21025a898783e       |
| build_os           | windows-x86_64                                 |
| build_target       | x86_64-pc-windows-msvc                         |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)            |
| rust_channel       | 1.70.0-x86_64-pc-windows-msvc                  |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)            |
| build_time         | 2023-09-19 19:00:31 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | default, sqlite, trash, which, zip             |
| installed_plugins  | gstat, query, query json, query web, query xml |

**Comment by fdncred** [comment]
correct, there is no code to restore a tab title. that may be something good to add.

**Comment by sibouras** [comment]
the current title with shell integration is quite long in a nested directory that it doesn't show the last directory name, so setting a custom title with only the name you want is useful

**Comment by sibouras** [comment]
with shell integration = true, wouldn't it override the custom title that you set when you enter a new command, this issue is about restoring the custom title after running a command like `npm help`

**Comment by paulie4** [comment]
I'm not sure what you are saying. Are you saying that it is currently working correctly (i.e. the title currently does restore), but it's possible that #6388 could be implemented in a way that breaks this functionality again? If that's what you are saying, couldn't we reopen this issue if that happens? Although, I would hope that whoever implements #6388 would do it in such a way that the custom title is not blown away when another command runs.

**Comment by sibouras** [comment]
> I'm not sure what you are saying. Are you saying that it is currently working correctly (i.e. the title currently does restore)

currently with shell integration = false, it does not restore
currently with shell integration = true, it does restore but the title is too long that it is unusable

this issue is about making the title restore with shell integration = false

issue #6388 doesn't mention restoring the title at all

**Comment by paulie4** [comment]
When would someone want to set `$env.config.shell_integration.osc2` to `false` (assuming that's what you meant when you said "shell integration = false")? It seems like we're just talking about the title being set when using the Nushell REPL, and "shell integration" to me sounds like using the REPL.

**Comment by sibouras** [comment]
yes im talking about `osc2`, and i want to set it to `false` because the title it sets is too long

**Comment by fdncred** [comment]
`shell_integration = true` isn't even a thing anymore. it sounds like this is fixed now.

**Comment by sibouras** [comment]
when i said shell_integration i meant `$env.config.shell_integration.osc2` and when its `false` the title doesn't restore, so this issue is not fixed

**Comment by fdncred** [comment]
That's the way it's supposed to work. Setting osc2 to false means don't set the title at all.

**Comment by sibouras** [comment]
powershell and cmd restore the title though

**Comment by fdncred** [comment]
I don't think cmd supports osc2 since it's an ansi escape sequence. Powershell may do something else to set the title, or it could use osc2 as well, but turning it off may stop it too.

**Comment by sibouras** [comment]
yes this issue is not about osc2 at all, i just want the title to restore like cmd


https://github.com/user-attachments/assets/6b33f7ee-868a-4849-88c5-c2c3eb18aa0e

**Comment by fdncred** [comment]
The title command in windows is windows specific, of course, so I doubt we'd create something like this. The best we can do is set titles in a custom command with ansi escapes.
```nushell
$env.config.shell_integration.osc2 = false
def title []: string -> string {
  $"\e]2;($in)(char bel)"
}
"test" | title
```
So, with osc2 set to false, it disables nushell from automatically setting the title. However, you can set the title by piping a string into the `title` custom command.

**Comment by sibouras** [comment]
yes i was already doing that, but i had to adjust the title manually everytime a command like `npm`, `lazygit`, `stylua`... runs until i gave up on tabs and using focus mode on windows-terminal, so its ok if this doesn't get implemented

**Comment by NotTheDr01ds** [comment]
@sibouras To make sure *your* title always gets displayed even if another command resets it, use the `pre_prompt` hook.  Here are a few examples, ranging from easiest to most "full functioning":

1. Simple override - Set title to *"My Title"*:

   ```nushell
   $env.config.hooks.pre_prompt = [
       { print $"(ansi title)My Title" }
   ]
   ```

2. Use an environment variable to change the title:

   ```nushell
   $env.NU_TITLE = "My Title"
   $env.config.hooks.pre_prompt = [
      { print $"(ansi title)($env.NU_TITLE)" }
   ]
   ```

3. An environment variable that can be a static string or dynamic closure (updates every new prompt):

   ```nushell
   $env.NU_TITLE = { date now }
   $env.config.hooks.pre_prompt = [{
     match ($env.NU_TITLE | describe) {
       string => { print $"(ansi title)($env.NU_TITLE)" }
       closure => { print $"(ansi title)(do $env.NU_TITLE)" }
     }
   }]
   ```

**Comment by sibouras** [comment]
@NotTheDr01ds that's almost perfect thank you, the thing that's missing is how to change the title after i run a tui, for example when i start helix and go to a file where the lsp is configured, when the lsp process starts it changes the title


https://github.com/user-attachments/assets/08ad3493-3c94-42dc-9c8d-d4e15d9eaf2c

with nvim there's `vim.uv.set_process_title` that allows me to change the title from within nvim, but for other tui's like lazygit and helix i don't have that, is there a way to do this in nushell?

**Comment by NotTheDr01ds** [comment]
@sibouras That's a good question, and I'm not 100% sure about that part -- I'm not that up to speed on how the LSP works.  I thought it ran "early" enough in the startup that OSC2 wouldn't even be in play, but perhaps I'm wrong.  @fdncred Any ideas there?

**Comment by ppena-LiveData** [comment]
@sibouras, is it easy for you to produce a minimal reproduction that we could try, cause it does not appear like you gave us enough detailed context to try to reproduce the exact problem you are seeing?

**Comment by paulie4** [comment]
@sibouras, is it easy for you to produce a minimal reproduction that we could try, cause it does not appear like you gave us enough detailed context to try to reproduce the exact problem you are seeing?

**Comment by sibouras** [comment]
the title changes once a file with a configured lsp is opened

https://github.com/user-attachments/assets/0488222e-3f50-41bd-aaf9-d966e878946d

for reproduction have lsp configured in nvim or helix then open a file and the title changes

**Comment by paulie4** [comment]
It sounds like you are asking if Nushell can change the title while another process is running. No, I don't think that would make sense, since the other process should be in charge of the title while it is running.

**Comment by NotTheDr01ds** [comment]
@sibouras Originally, I thought you were saying that Nushell didn't set the title *back* to your title *after* running Helix, but now I'm not sure.  If you are simply trying to suppress the title change done by Helix when it *starts*, then I agree with @paulie4 that this would have to be controlled in Helix.  I can't think of a way for the shell (even Bash or Zsh) to prevent a subprocess from sending the OSC codes to change the title.

Is this something you can do in another shell?

**Comment by sibouras** [comment]
in wsl the title doesn't change when the lsp starts inside the editor


https://github.com/user-attachments/assets/55f911d2-f008-4981-afec-de6bbc8cbed0
