### ISSUE TITLE
nushell 0.94.1 breaks Windows path handling

### ISSUE THREAD

**Issue by CarterLi** [nushell/nushell#13016]
### Describe the bug

```
Error:   × Invalid literal
     ╭─[C:\Users\zhang\AppData\Roaming\nushell\config.nu:792:17]
 791 │ #use ~/.starship.nu
 792 │ alias curl = c:\msys64\clangarm64\bin\curl.exe
     ·                 ───────────────┬──────────────
     ·                                ╰── unrecognized escape after '\' in string
 793 │ alias vim = nvim
     ╰────
```

### How to reproduce

Windows style paths in config file result in error `unrecognized escape after '\' in string`

### Expected behavior

Don't error

### Screenshots

N/A

### Configuration

N/A

### Additional context

Regression in 0.94.1. It worked in 0.94.0

**Comment by YizhePKU** [comment]
@devyn Probably a side-effect of #13001.

**Comment by Deebster** [comment]
You can replace each backslash with a double backslash, but it's very tedious to do this outside of scripts.

I've downgraded until it's fixed with `cargo install --version 0.94.0 nu`

**Comment by CarterLi** [comment]
starship generates nu scripts with Windows style paths.

BTW starship works weird after upgrading nu to 0.94.0+

**Comment by chtenb** [comment]
Huh, I downgraded to 0.94.0 again, but the issue persists, as in, my config scripts that worked earlier on 0.94.0 no longer work after downgrading from 0.94.1!

**Comment by kubouch** [comment]
On my Windows end, the issue appears at 0.94.1. The version 0.94.0 works fine.

**Comment by rogtino** [comment]
Hello team,would you mind posting a bug fix release?

**Comment by xd003** [comment]
I am still facing this issue on latest nushell version 0.100.0

```
❯ 7z x "C:\Users\Admin\Documents\archive.zip"
Error:   × Invalid literal
   ╭─[entry #3:1:9]
 1 │ 7z x "C:\Users\Admin\Documents\archive.zip"
   ·         ─────────────────┬─────────────────
   ·                          ╰── unrecognized escape after '\' in string
   ╰────

❯ nu --version
0.100.0
```

**Comment by kubouch** [comment]
`"` denotes escaped strings, like in JSON. It's better to use non-escaped strings (`'`) for Windows paths (or use forward slashes).
