### ISSUE TITLE
the catch block doesn't run when script is interrupted by the user

### ISSUE THREAD

**Issue by name-snrl** [nushell/nushell#13394]
### Describe the bug

I'm writing a script that creates a temporary directory, and I'd like the script to delete it when it terminates(no matter how). If `try` block terminates with an error, the directory is deleted, but if I interrupt it, nothing happens.

### How to reproduce

run the script below, then interrupt it.

```nu
#!/usr/bin/env nu

let tmp = mktemp --directory
print $tmp
try {
    sleep 10sec
} catch {
    rm -rf $tmp
}
rm -rf $tmp
```

check the printed path
directory still exists :(

### Expected behavior

the directory is deleted when the script is interrupted

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.92.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) (built from a source tarball) |
| cargo_version      | cargo 1.77.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which                                     |
| installed_plugins  |                                                                   |

**Comment by NotTheDr01ds** [comment]
Would that be a form of a `finally` block?

**Comment by 132ikl** [comment]
I'm going to merge this into #15279, which should solve this issue as well. @name-snrl if you think `try {} finally {}` wouldn't address your needs, feel free to re-open this.

**Comment by onsah** [comment]
`finally` still doesn't solve this problem. Could you reopen?

Here is an example script that interrupt doesn't execute the `finally` block:

```nu
try {
  loop { sleep 10ms }
} finally {
  print "cancelled"
}
```

## Expected behaviour

Print `cancelled`

## Actual Behaviour

```
^CError: nu::shell::error

  × Operation interrupted
   ╭─[repl_entry #1:1:45]
 1 │ try { loop { sleep 10ms } } finally { print "cancelled" }
   ·                                             ─────┬─────
   ·                                                  ╰── This operation was interrupted
   ╰────
```
