### ISSUE TITLE
Path completion with tab, when path have spaces in it, do not work

### ISSUE THREAD

**Issue by vksdev** [nushell/nushell#16712]
To reproduce try launching a program installed in "C:\Program Files\" for example "C:\Program Files\7-zip\7z-FM.exe" using tab completions. You will notice that it works upto `C:\Program Files` after that it finds no records.

**Comment by fdncred** [comment]
Agreed. I have a problem with it too on Windows. Just confirmed it.

**Comment by cptpiepmatz** [comment]
This lines causes the completer not to find any more entries. https://github.com/nushell/nushell/blob/9ebb02d23691a373298ac019d5081df508513733/crates/nu-cli/src/completions/completer.rs#L557

Just putting a `|_| false` fixes that, but I guess that might break other things🤔

**Comment by cptpiepmatz** [comment]
Also this issue is cross platform

**Comment by blindFS** [comment]
> This lines causes the completer not to find any more entries.
> 
> [nushell/crates/nu-cli/src/completions/completer.rs](https://github.com/nushell/nushell/blob/9ebb02d23691a373298ac019d5081df508513733/crates/nu-cli/src/completions/completer.rs#L557)
> 
> Line 557 in [9ebb02d](/nushell/nushell/commit/9ebb02d23691a373298ac019d5081df508513733)
> 
>  |c| *c == b' ', 
> Just putting a `|_| false` fixes that, but I guess that might break other things🤔

I think a simple solution would be to include both results for
1. the last word
2. the whole expression text

In most cases the matcher will rule out unwanted entries for us.

**Comment by cptpiepmatz** [comment]
I'm trying something out. Let's see if that works first

**Comment by blindFS** [comment]
@cptpiepmatz As I recall, the very reason I did the split by space at that place is for this test case

https://github.com/nushell/nushell/blob/9ebb02d23691a373298ac019d5081df508513733/crates/nu-cli/tests/completions/mod.rs#L181-L190

Which does not make much sense itself, maybe we want to revisit that as well.

**Comment by ysthakur** [comment]
Should be fixed by https://github.com/nushell/nushell/pull/16715

**Comment by blindFS** [comment]
@ysthakur It turns out the solution of #16715 is still not perfect.

For example:

```
mkdir "`a b`/c"
```

This time, the path is quoted with `'`, leading to a different parsed expression (probably a string) and it will trigger the fallback completion once again.

I'm wondering that maybe we don't need the test case in my last comment at all.
As a result, no longer split the context by space in the fallback section and suddenly it makes things easier.

**Comment by blindFS** [comment]
And if you run
```
mkdir "`a b`/c"
```
in the home directory. During completion, only that one gets `~` expanded, which is another issue of inconsistency.

**Comment by ysthakur** [comment]
Aww, okay. I was going to ask if it was possible to avoid space-splitting in the first place in your last PR, but I thought this issue was only for external commands. We can leave the changes in for now since they do fix that one case, at least.

**Comment by blindFS** [comment]
> Aww, okay. I was going to ask if it was possible to avoid space-splitting in the first place in your last CR, but I thought this issue was only for external commands. We can leave the changes in for now since they do fix that one case, at least.

Yeah, I'm just saying that we might need to revisit the necessity of the whole rsplit hack. I don't find any real use case of it but I think you may think of some.
