### ISSUE TITLE
ps builtin reports cpu column as 0.000 for all processes on Apple Silicon M1

### ISSUE THREAD

**Issue by obaudys** [nushell/nushell#4142]
### Describe the bug

The `ps` builtin on my Macbook Pro M1 does not show anything other than 0.000 in the 'cpu' column.

I have a proposed solution below.

### How to reproduce

1.  Start a busy process, eg.
```
$ python
Python 2.7.7 (v2.7.7:f89216059edf, May 31 2014, 12:53:48) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> x = 0
>>> while True:
...     x += 1
... 
```
2. `ps | where cpu > 0`
3.  observe no ouput.

### Expected behavior

I expected nu to approximate the %cpu output of eg.  
`/bin/ps -caxo pid,pcpu,pmem,comm=20 | awk '$2 > 0{print}NR==1{print}'

### Screenshots

![image](https://user-images.githubusercontent.com/53287664/142854836-51a33b05-35b3-43c0-9762-11eba2961244.png)

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|build_os|macos-aarch64|
|rust_version|rustc 1.54.0 (a178d0322 2021-07-26)|
|rust_channel|stable-aarch64-apple-darwin (default)|
|cargo_version|cargo 1.54.0 (5ae8d74b3 2021-06-22)|
|pkg_version|0.40.0|
|build_time|2021-11-19 14:24:04 +11:00|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, which, zip|
|installed_plugins|fetch, match, post, ps, sys|

### Additional context

I had a look at what is possibly causing this,  and it seems that in the upstream `sysinfo` crate (the version used in HEAD at least), the cpu time is zeroed in the initial calls to `System::new_all()` and `System::refresh_all()`, and requires and addition refresh to get an

I found that sleeping for 50ms and calling `System::refresh_processes()` approximates the output of `/bin/ps -caxo pid,pcpu,pmem,comm`.  I say approximates because the %cpu reported by /bin/ps fluctuates wildly each invocation, and I do the

The 50ms sleep may be really unpalatable.  It appears `/bin/ps` does not sleep at all; the man page claims "this is a decaying average over up to a minute of previous (real) time",  but looking at the code for ps [https://opensource.apple.com/source/adv_cmds/adv_cmds-176.100.1/ps/] it appears to be populated from the kernel directly via a `struct thread_basic_info.cpu_usage;      /* scaled cpu usage percentage */`. 

If we want to do it that way, it will need to be sent upstream to the sysinfo crate.  Anyway, here's my proposed solution:
```
diff --git a/crates/nu-command/src/commands/system/ps.rs b/crates/nu-command/src/commands/system/ps.rs
index 85dc6400..a01636b7 100644
--- a/crates/nu-command/src/commands/system/ps.rs
+++ b/crates/nu-command/src/commands/system/ps.rs
@@ -2,6 +2,7 @@ use crate::prelude::*;
 use nu_errors::ShellError;
 use nu_protocol::{Signature, TaggedDictBuilder, UntaggedValue};
 use sysinfo::{ProcessExt, System, SystemExt};
+use std::{thread, time};
 
 pub struct Command;
 
@@ -42,6 +43,8 @@ fn run_ps(args: CommandArgs) -> Result<OutputStream, ShellError> {
     let long = args.has_flag("long");
     let mut sys = System::new_all();
     sys.refresh_all();
+    thread::sleep(time::Duration::from_millis(50));
+    sys.refresh_processes();
 
     let mut output = vec![];

```

![image](https://user-images.githubusercontent.com/53287664/142856811-9f8196ec-ba44-4255-9823-82ec3a3e9620.png)

**Comment by fdncred** [comment]
Thanks for the research and suggestion!

We used to have sleep in there but people complained about it https://github.com/nushell/nushell/issues/3402. https://github.com/nushell/nushell/pull/3407. Maybe 50 ms is more palatable than 500 ms.

I'd say go ahead and submit a PR.

**Comment by obaudys** [comment]
I suspect that nobody noticed that the previous fixes broke the CPU metrics.  The sysinfo crate ships with an example (simple.rs) that only shows process cpu usage for me after I refresh twice; this is in accordance with the crate's docs.

**Comment by obaudys** [comment]
> I suspect that nobody noticed that the previous fixes broke the CPU metrics. The sysinfo crate ships with an example (simple.rs) that only shows process cpu usage for me after I refresh twice; this is in accordance with the crate's docs.

I've just tried commit b93b80cc, and it does indeed still work.   I'll try a git bisect later and see where it breaks.

**Comment by obaudys** [comment]
According to git bisect, the issue started with 08014c6a9857c94dfab14e4b32414082201bd655.

However commit b93b80cc broke cpu usage in another way:  the python busy while loop example above does not show up in `ps | where cpu > 1`.  It looks like we need a `sleep(); refresh()` step to get any accuracy at all.

**Comment by Weiyi-Feng** [comment]
Same issue in windows 10 20H2

**Comment by fdncred** [comment]
we've done some work on this recently but unfortunately it still doesn't seem to work when compared with this command `^/bin/ps -caxo pid,pcpu,pmem,comm=20 | awk '$2 > 0{print}NR==1{print}'`

**Comment by amtoine** [comment]
Hi everyone :wave: :yum: 

i've switched to `nushell` as my daily shell recently :tada: 

# The issue
i have the same problem as above:
- tried to run an expensive job, taking up to 100% of one of the cores of my machine
```python
x = 0
while True:
  x += 1
```
- `ps | where cpu > 0` gives me nothing
- `/bin/ps -caxo pid,pcpu,pmem,comm=20 | awk '$2 > 0{print}NR==1{print}' | grep python` gives me `9505 74.2  0.1 python`

Just to let you know the problem is not specific to the _Apple Silicon M1_ :wink:

# My local setup
|key|value|
|-|-|
|version|0.66.0|
|branch||
|commit_hash|c6cb491e776958696756cd864901810d0ab50ac3|
|build_os|linux-x86_64|
|build_target|x86_64-unknown-linux-gnu|
|rust_version|rustc 1.62.1 (Arch Linux rust 1:1.62.1-1)|
|cargo_version|cargo 1.62.1|
|pkg_version|0.66.0|
|build_time|2022-07-26 23:09:45 +00:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins||

**Comment by fdncred** [comment]
We would love for someone to resolve this prickly issue. We have looked at it several times and hacked together pieces of several crates to get it to work in all platforms. Alas, it does work for everyone.

**Comment by amtoine** [comment]
> We would love for someone to resolve this prickly issue. We have looked at it several times and hacked together pieces of several crates to get it to work in all platforms. Alas, it does work for everyone.
> 
so it should be working by now? :thinking:

**Comment by fdncred** [comment]
Sorry for the confusion. I meant to say that it does not work for everyone.

**Comment by amtoine** [comment]
> Sorry for the confusion. I meant to say that it does not work for everyone.
>
oooooh :open_mouth:

no worries :yum: 

i could not find any PR related to this, **is there any public work on that `ps` issue?** :thinking: 
i'm very new to `nushell` and `rust`, but investigating is always a good way to learn! :ok_hand:

**Comment by fdncred** [comment]
I doubt anyone is working on it. Feel free to try and fix it.

**Comment by amtoine** [comment]
> I doubt anyone is working on it. Feel free to try and fix it.
>
got it :wink:

that issue won't close until the bug goes away :muscle: :yum:

**Comment by obaudys** [comment]
It seems since this was raised, the code has been restructured and now uses libproc.

So I've done some digging and I think I have resolved the issue:  it seems that the cpu times returned by libproc are in mach tick units, not nanoseconds.  This is not very well documented!  I'm now getting accurate CPU usage metrics.

I've fixed the issue created pull request #6457

**Comment by hustcer** [comment]
Should be fixed by https://github.com/nushell/nushell/pull/6457, Please reopen if not

**Comment by amtoine** [comment]
hello there :wave: 

i still have the issue with the last `git` version of `nushell` :confused: 

## the issue
```rust
> ps | where cpu > 0
```
gives no result

## building
```rust
cargo build --workspace --features=extra
cargo run --features=extra
```

## version
```rust
╭────────────────────┬─────────────────────────────────────────────────╮
│ version            │ 0.67.1                                          │
│ branch             │ main                                            │
│ commit_hash        │ e81689f2c0ca8e1d2e3b208cfcb4418692acea80        │
│ build_os           │ linux-x86_64                                    │
│ build_target       │ x86_64-unknown-linux-gnu                        │
│ rust_version       │ rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       │
│ cargo_version      │ cargo 1.63.0                                    │
│ pkg_version        │ 0.67.1                                          │
│ build_time         │ 2022-09-04 11:57:00 +02:00                      │
│ build_rust_channel │ debug                                           │
│ features           │ database, dataframe, default, trash, which, zip │
│ installed_plugins  │                                                 │
╰────────────────────┴─────────────────────────────────────────────────╯
```

**Comment by obaudys** [comment]
@amtoine I see you are running on Linux.  This issue here is specific to MacOS; specifically running on the M1 chip.

There's issues with the `ps` command in Linux,  eg. #6101.  Out of interest, does the `ps` command return anything at all even without the `where`?  If not, try this:
```
prlimit --nofile=65536 cargo run
```
Does `ps` work now?   Then you are affected by #6101.   Looks like the CPU usage is broken anyway on linux even with the ulimit workaround.

**Comment by obaudys** [comment]
@amtoine I see you are running on Linux.  This issue here is specific to MacOS; specifically running on the M1 chip.

There's issues with the `ps` command in Linux,  eg. #6101.  Out of interest, does the `ps` command return anything at all even without the `where`?  If not, try this:
```
prlimit --nofile=65536 cargo run
```
Does `ps` work now?   Then you are affected by #6101.   Looks like the CPU usage is broken anyway on linux even with the ulimit workaround.  Edit: CPU usage is reported as 0% on linux specifically because of that issue:  the process' cpu times are read lazily and the before and after times are identical.

**Comment by amtoine** [comment]
@obaudys

> @amtoine I see you are running on Linux. This issue here is specific to MacOS; specifically running on the M1 chip.
> 
ooh yes you're right my bad :eyes:

> There's issues with the `ps` command in Linux, eg. #6101. Out of interest, does the `ps` command return anything at all even without the `where`? If not, try this:
> 
yes i have some ouput with the `ps` comand, without the `where` :+1: 

> ```
> prlimit --nofile=65536 cargo run
> ```
> 
> Does `ps` work now?
>
from the tip of the `main` branch, it does not work any better no :confused:

**Comment by rgwood** [comment]
@amtoine btw `ps` CPU usage should be fixed on Linux as of October: https://github.com/nushell/nushell/pull/6858
