### ISSUE TITLE
Custom types and/or ability to use records as function arguments

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5030]
### Related problem

I am trying to write a function that accepts a record as an argument and enforces fields and types of that record

### Describe the solution you'd like

something like:
`def function [
  arg:record<string,int,bool>
] {}`

or
`let my_type = {
field1: string
field2:int
field3:bool
}
def function [
  arg: my_type
] {}`

### Describe alternatives you've considered

You can specify the argument as any and then write the validation within the function but that's cumbersome, it's better if this was done automatically by the type system

**Comment by fdncred** [comment]
Just to not repeat ourselves too much, I've suggested using the `any` type which works, but isn't exactly what @Yethal was looking for. See more details here https://discord.com/channels/601130461678272522/614593951969574961/958697010914025503

**Comment by hustcer** [comment]
Resolved by this PR: https://github.com/nushell/nushell/pull/5040

**Comment by Yethal** [comment]
@hustcer Linked PR does not fully resolve the issue, while it is possible to specify record as an argument type it is not possible to specify the types for the record fields. Instead of just `arg:record` I'd like to be able to specify `arg:record<string,int,bool>` so that the validation of the input shape is done by the type system

**Comment by jntrnr** [comment]
This works in latest main

```
> def function [ arg:record<a:string,b:int,c:bool> ] {}
~/Source/nushell> function {a: "bob"}
Error: nu::parser::type_mismatch

  × Type mismatch.
   ╭─[entry #12:1:1]
 1 │ function {a: "bob"}
   ·          ─────┬────
   ·               ╰── expected record<a: string, b: int, c: bool>, found record<a: string>
   ╰────
```
