### ISSUE TITLE
Auto completion for native excutables on PATH.

### ISSUE THREAD

**Issue by NoahELE** [nushell/nushell#5622]
### Related problem

Nushell is currently not able to auto complete native excutables on PATH.

### Describe the solution you'd like

When using `tab` completion, it is better to show both internal functions and excutables on PATH.

**Comment by sholderbach** [comment]
I think this is solved with the upcoming version `0.63.0` 
![image](https://user-images.githubusercontent.com/15833959/169985148-0216ae68-5fb6-4cec-9424-1aece2b4490b.png)

For the flags and parameters we need to create the appropriate definittions. You can find some of them in https://github.com/nushell/nu_scripts/tree/main/custom-completions

**Comment by NoahELE** [comment]
> I think this is solved with the upcoming version `0.63.0` ![image](https://user-images.githubusercontent.com/15833959/169985148-0216ae68-5fb6-4cec-9424-1aece2b4490b.png)
> 
> For the flags and parameters we need to create the appropriate definittions. You can find some of them in https://github.com/nushell/nu_scripts/tree/main/custom-completions

I've updated to 0.63, but still cannot complete path excutables. Is this feature not available in 0.63 yet?

**Comment by sholderbach** [comment]
Mhh maybe there is difference in behavior on Linux compared to Windows? Are you running a recent configuration with `config.nu` and `env.nu`?

**Comment by NoahELE** [comment]
Yep, delete the old ones and let nushell generate a new config.nu and env.nu.

**Comment by NoahELE** [comment]
Also, I am using nushell on Windows installed by scoop. Can someone confirm whether it is a common problem on Windows?

**Comment by adzubla** [comment]
I believe there is a configuration to enable completion of external files, but I cant find any reference to it...

**Comment by hornyjailfish** [comment]
i had this issue too 
gone then add to my `$nu.env-path`
`let-env PATH = ($env.Path | split row (char esep) )`

**Comment by NoahELE** [comment]
> i had this issue too gone then add to my `$nu.env-path` `let-env PATH = ($env.Path | split row (char esep) )`

Solved. Works for me on Windows. Thanks
