### ISSUE TITLE
Panic when completing multi-line command where the last command contains '$in'.

### ISSUE THREAD

**Issue by IanManske** [nushell/nushell#5716]
### Describe the bug

The bug might be more general than the title and this description, but it involves completing one command (the first or second?) in a multi-line pipeline command. If the last (piped) command uses `$in`, then nu panics when the completion is requested.

### How to reproduce

1. Copy + paste the following into the command line:
```
(
  ls
  | append []
  | insert something { $in }
)
```
2. Use the arrow keys, etc, to move the cursor after `ls` (on the same line). 
3. Press tab to attempt a completion and panic nu.

For some reason the `append []` is necessary to trigger the panic. Some, but not all, other commands can be used instead. E.g., `take 100` or `update name { $in }` but not `first` or `reject nothing`.

Similarly, `$in` in one form or another is necessary for the panic:
- `insert something $in`
- `update name { $in.name }`

Using a named variable does not cause a panic: `insert something { |x| $x }`.

### Expected behavior

No panic plz :)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.1                                          |
| branch             |                                                 |
| commit_hash        | 6c07bc10e2cf3445e098089d184b86463c0a330a        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (Arch Linux rust 1:1.61.0-1)       |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.63.1                                          |
| build_time         | 2022-05-29 02:16:59 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

Bug also occurs on latest commit e4a2279 (compiled and ran from source).

### Additional context

With my limited rust and nu knowledge, I think it has something to do with the parser?
The example above causes the parser to give a `Span` with `start` and `end` of `0`.
I think this invalid `Span` then messes with the logic for `fetch` in `command_completions.rs`.
I.e, lines 165-180, but with a emphasis on the `skip_while`:
```rust
let last = self
    .flattened
    .iter()
    .rev()
    .skip_while(|x| x.0.end > pos) // prematurely stops due to the invalid Span
    .take_while(|x| {
        matches!(
            x.1,
            FlatShape::InternalCall
                | FlatShape::External
                | FlatShape::ExternalArg
                | FlatShape::Literal
                | FlatShape::String
        )
    })
    .last();
```
Down the line, this causes another span to have an improper `start`. This eventually leads to an invalid string slice and a panic.

**Comment by merelymyself** [comment]
This issue has been resolved, I think. Might have been by https://github.com/nushell/reedline/pull/446

**Comment by IanManske** [comment]
Just an update, the panic no longer occurs if the cursor is after `ls`. But a panic can still happen if the cursor is anywhere before `ls` (not just the same line) or if the cursor is just before/inside the `[]` in `append`. This is with nu version 0.65.0.

**Comment by IanManske** [comment]
Closed with #6287's fix.
