### ISSUE TITLE
Completion menu does not work for aliases

### ISSUE THREAD

**Issue by zim0369** [nushell/nushell#5888]
### Describe the bug

For aliases like `l=ls` the completion menu doesn't work. User sees `#NO RECORD`

### How to reproduce

1. Make an alias `l=ls`
2. reload config
3. type `l ` in prompt
4. press `tab`
5. `#NO RECORDS`

### Expected behavior

Completion menus should appear for aliases.

**Comment by merelymyself** [comment]
It's working for me.

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.64.1                                   |
| branch             | main                                     |
| commit_hash        | 533e04a60a3bf28e34420f8e29e0f6d070ed49d1 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)        |
| pkg_version        | 0.64.1                                   |
| build_time         | 2022-06-24 20:45:51 +08:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by skelly37** [comment]
Latest stable release here, also doesn't work, maybe it got fixed in 0.64.1, as in @merelymyself 
![image](https://user-images.githubusercontent.com/76530971/175819392-274eec62-8568-46bd-9ab0-c733a05f14c6.png)

**Comment by kubouch** [comment]
Seems like it's fixed nowadays. Please, reopen if you still have the problem.

**Comment by claymorwan** [comment]
I personally still have an issue with this when using a completion and liases sourced from 2 different files.
For example the git completion and aliases from the nu_script repo, when i use let's say `git remote` the completion shows but when i do `gr` (alias for `git remote`) it doesn't
```
$ | git remote
home/
system/
git remote add      Add a new tracked repository
git remote get-url  Get the URL for a tracked repository
git remote remove   Remove a tracked repository
git remote rename   Rename a tracked repository
git remote set-url  Set the URL for a tracked repository
$ | gr
home/               system/
```
Apparently sourcing the completion then the aliases should fix it but it didn't
