### ISSUE TITLE
Tracking issue for `0.83.0` fixup

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#9812]
The type system changes and a few other breaking changes with https://github.com/nushell/nushell/releases/tag/0.83.0 have caused issues with existing scripts or tooling integrations that were not foreseen.
If we want to resolve them soon the following problems should be resolved for a patch release:

## Patch release plan for `0.83.1`
We (@nushell/core-team) want to resolve the type system related regressions, as soon as we collected the majority of issues (grace period for some of the package manager downloads).

The dataframe command fix appears to require signficant work, so will be postponed from the urgent patch release, or based on how many folks are ready to implement and test it. If they are not ready we will ship the finished fixes for the standard features regardless.

### Commands with ambiguous output types fail
Commands that have multiple output types for the same input type break with the current type checking logic.
The type checking logic will assign the output type based on the first found matching input type. Thus if you expect to be able to use the other output types with a restrictive downstream command this will fail if the signature is not right.
- https://github.com/nushell/nushell/issues/9808
- `append`/`prepend` as discussed based on #9720
- See also #9788 as `into duration` suffers from this (if this is not found to be an issue we will not ship this with the hotfix as it is a breaking change)
- Probably a few more commands
- We should systematically check for this!
- https://github.com/nushell/nushell/pull/9827
- https://github.com/nushell/nushell/pull/9828
- `transpose` had ambiguous output types that breaks `load-env`: https://github.com/nushell/nushell/pull/9842
- https://github.com/nushell/nushell/pull/9830

### Rest parameter lists surface the wrong type to the function body
- https://github.com/nushell/nushell/issues/9809
- #9720
- https://github.com/ajeetdsouza/zoxide/issues/595
- Seems to have been originally described by https://github.com/nushell/nushell/issues/9058 but is now a more pressing issue.
This will probably require some internal changes to have a clear type in the signature and the correct type in the function body.

### Dataframe support is broken
Due to the removal of the old `input_type` and `output_type` that were only there for the ill-fated dataframe overloading (https://github.com/nushell/nushell/pull/9677) and a potential lack of `Type::Custom("...")` in the `input_output_type` pairs (see https://github.com/nushell/nushell/pull/9515) the use of dataframes appears to be broken.
- https://github.com/nushell/nushell/issues/9807
- https://github.com/nushell/nushell/issues/9806

### Remaining limits for broadcast operations
- #9793 
- #9777 Plugins need to be updated if they used `vectorizes_over_list`

### Overly narrow type signatures
Some commands support more types in their implementation than they declare. If reasonable we should fix the signature. If we think a broader signature is unsound, the implementation needs to be corrected.
- #9813 

## Other
Caused by the `let-env` removal in #9574 
- https://github.com/starship/starship/issues/5338 (patch already landed on main but not released yet)
- https://github.com/nushell/nushell/discussions/9804

**Comment by amtoine** [comment]
## :warning: do not forget to keep the following updated when we release
- https://github.com/ajeetdsouza/zoxide/issues/595
- https://github.com/ajeetdsouza/zoxide/pull/596
- https://github.com/starship/starship/issues/5338

**Comment by sholderbach** [comment]
Done as https://github.com/nushell/nushell/releases/tag/0.83.1 is released

**Comment by CarterLi** [comment]
Still get error with zoxide even with nightly build of zoxide

```
Error: nu::parser::expected_keyword

  × Expected keyword.
    ╭─[C:\Users\zhang\.zoxide.nu:8:1]
  8 │ # Initialize hook to add new entries to the database.
  9 │ if (not ($env | default false __zoxide_hooked | get __zoxide_hooked)) {
    · ─┬
    ·  ╰── expected def, def-env, extern, alias, use, module, export or export-env keyword
 10 │   $env.__zoxide_hooked = true
    ╰────
```

Note the stable build of zoxide still uses `let-env`
