### ISSUE TITLE
'watch' not calling closure when file is modified [Windows+Linux]

### ISSUE THREAD

**Issue by marshrayms** [nushell/nushell#9910]
On Windows, when a file is modified, I receive the following `--verbose` output:

```[DebouncedEvent { event: Event { kind: Modify(Any), paths: ["C:\\full\\path\\to\\modified_file.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }, time: Instant { t: 532.0783789s } }]```

But my closure is not called.

It appears that the `notify` library is returning EventKind::Modify([ModifyKind::Any](https://github.com/notify-rs/notify/blob/5f40b83c04b04893a42f91b55e4ceeef3777d47c/notify/src/event.rs#L154)), said to be "The catch-all case, to be used when the specific kind of event is unknown."

Looking at the [code in watch.rs](https://github.com/nushell/nushell/blob/a98b3124c52262d0a72c4d009cfc86ee0977bb0d/crates/nu-command/src/filesystem/watch.rs#L259), the `ModifyKind::Any` case appears to be skipped. I think that would explain why my closure is not being called.

Can we please add support for calling the supplied closure in the `ModifyKind::Any` case?

Thanks!

- Marsh

```
╭────────────────────┬───────────────────────────────────────────────╮
│ version            │ 0.83.1                                        │
│ branch             │                                               │
│ commit_hash        │                                               │
│ build_os           │ windows-x86_64                                │
│ build_target       │ x86_64-pc-windows-msvc                        │
│ rust_version       │ rustc 1.71.0 (8ede3aae2 2023-07-12)           │
│ rust_channel       │ stable-x86_64-pc-windows-msvc                 │
│ cargo_version      │ cargo 1.71.0 (cfd3bbd8f 2023-06-08)           │
│ build_time         │ 2023-08-03 14:18:22 -07:00                    │
│ build_rust_channel │ release                                       │
│ allocator          │ standard                                      │
│ features           │ dataframe, default, sqlite, trash, which, zip │
│ installed_plugins  │                                               │
╰────────────────────┴───────────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
Seems like a reasonable request. We'd most likely accept a PR that introduces this change. One might also call this change a bug, but I'm not really sure.

**Comment by MrFoxPro** [comment]
> Seems like a reasonable request. We'd most likely accept a PR that introduces this change. One might also call this change a bug, but I'm not really sure.

This is same on Linux: 
https://github.com/nushell/nushell/assets/17229619/3acb938f-f6f3-4d9f-9043-3c0480c8da70

**Comment by rgwood** [comment]
This is fixed in `main` and the fix will be out in v0.84 on August 22. Thanks for the detailed reports and sorry for the inconvenience!

**Comment by gfgafn** [comment]
It still doesn't seem to be fixed.
<img width="1280" alt="image" src="https://github.com/nushell/nushell/assets/87858323/573dfddd-2f36-4665-bf5e-6e24d3bd9c97">


| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.0                                   |
| branch             |                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-08-22 21:20:58 +00:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by rgwood** [comment]
Ah, darn; I suspect this is fixed for Linux but not Windows (I was testing on Linux).

I handled `EventKind::Modify(ModifyKind::Data(DataChange::Any))` but it looks like changes are being reported as `EventKind::Modify(ModifyKind::Any)` on Windows.

Should be an easy PR for anyone who has time (just needs a bit of testing on a few OSs). If nobody else gets to it I'll try to fix it in the next week.

**Comment by rgwood** [comment]
As an aside, the reason this is happening:

[The library we are using for filesystem notifications](https://github.com/notify-rs/notify) made some big changes; they used to try hard to provide a consistent high-level functionality across OSs, but they kinda gave up on that because filesystem behaviour varies a lot across OSs.

So now we're getting filesystem notification info that's a little different on every OS, and unfortunately we don't have any tests for `watch` to catch bugs. I'd love to add tests eventually, but they will be a little tricky to write and very different from most of our existing tests.

**Comment by rgwood** [comment]
This has been fixed on Windows. To get the fix you'll need to wait for the 0.85 release in 3 weeks (sorry!) or clone the repo and build from source.

**Comment by hustcer** [comment]
Don't forget that we have nightly release now: https://github.com/nushell/nightly/releases

**Comment by gfgafn** [comment]
@rgwood  I built it from source and it works. Thank you very much!

@hustcer Thank you for bringing this to my attention. It appears that the PR #10109 was not included in the latest nightly release on August 24, 2023. By the way, it would be more beneficial to have a changelog included in the release notes. Currently, the release notes for nightly releases do not contain a changelog, making it time-consuming to identify the changes or fixes.

**Comment by hustcer** [comment]
> By the way, it would be more beneficial to have a changelog included in the release notes. Currently, the release notes for nightly releases do not contain a changelog, making it time-consuming to identify the changes or fixes.

@gfgafn That's a good idea, currently we didn't follow the [commit conventions](https://www.conventionalcommits.org/en/v1.0.0/), however, maybe I can create a commit log as the CHANGELOG
